region: fix misleading-indentation warning
Werror is on so breaks efi build on newer GCC's (using 8.1.1)

/home/jhli/Workspace/cr/ipmctl/DcpmPkg/driver/Core/Region.c:376:7: error: this if clause does not guard... [-Werror=misleading-indentation]
       if (EFI_NO_RESPONSE == ReturnCode)
       ^~
/home/jhli/Workspace/cr/ipmctl/DcpmPkg/driver/Core/Region.c:381:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the if
         continue;
         ^~~~~~~~

Signed-off-by: Juston Li <juston.li@intel.com>